spring.datasource.url=jdbc:mysql://root:bZAeoAKyFcGPHzCOByVscBfSMPSfSXLV@monorail.proxy.rlwy.net:34981/railway:3306/railway
spring.datasource.username=root
spring.datasource.password=bZAeoAKyFcGPHzCOByVscBfSMPSfSXLV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false